import _analytics from './analytics'; // 应用分析代码
import _connect from './connect'; // 接口访问
import _device from './device'; // 设备访问
import _district from './district'; // 地区操作
import _history from './history'; // 浏览器历史记录
import _pgyer from './pgyer'; // 蒲公英
import _router from './router'; // 路由跳转
import _talkingData from './talkingData'; // 埋点
import _utils from './utils'; // 工具类
import _weixin from './weixin'; // 微信

export { _analytics as Analytics };
export { _connect as Connect };
export { _device as Device };
export { _district as District };
export { _history as History };
export { _pgyer as Pgyer };
export { _router as Router };
export { _talkingData as TalkingData };
export { _utils as Utils };
export { _weixin as Weixin };
